swagger: '2.0'
info:
  title: MCP Server
  description: A MCP to use our Jira Instance
  version: 1.0.0
host: <azure-function-app-name>.azurewebsites.net
basePath: /
schemes:
  - https
consumes: []
produces: []
paths:
  /:
    post:
      summary: JIRA MCP Server
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: InvokeMCP
      responses:
        '200':
          description: Success
definitions: {}
parameters: {}
responses: {}
securityDefinitions:
  api_key:
    type: apiKey
    in: header
    name: X-API-KEY
security:
  - api_key: []
tags: []
